x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100m

services:
  server:
    image: judge0/judge0:1.13.0
    volumes:
      - ./judge0.conf:/judge0.conf:ro
      - ./problems:/dev/problems
    ports:
      - "2358:2358"
    privileged: true
    <<: *default-logging
    restart: always

  workers:
    image: judge0/judge0:1.13.0
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
      - ./problems:/dev/problems
    privileged: true
    <<: *default-logging
    restart: always

  db:
    image: postgres:13.0
    env_file: judge0.conf
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always

  redis:
    image: redis:6.0
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.conf
    volumes:
      - redis-data:/data
    <<: *default-logging
    restart: always

#  postgres:
#    image: postgres:15-alpine
#    container_name: hustforces-postgres
#    environment:
#      POSTGRES_DB: hustforces
#      POSTGRES_USER: hustforces
#      POSTGRES_PASSWORD: hustforces123
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    networks:
#      - hustforces-network
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U hustforces" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5

#networks:
#  hustforces-network:
#    driver: bridge

volumes:
  postgres-data:
  redis-data:
  postgres_data: