services:
  judge0:
    image: judge0/judge0:latest-dev
    build:
      context: .
      target: development
    volumes:
      - .:/api
    ports:
      - "2358:2358"
      - "3001:3001" # For ./scripts/dev/serve-docs
    privileged: true

  db:
    image: postgres:16.2
    env_file: judge0.conf
    volumes:
      - data:/var/lib/postgresql/data/
    restart: always

  redis:
    image: redis:7.2.4
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.conf
    restart: always

  postgres:
    image: postgres:15-alpine
    container_name: hustforces-postgres
    environment:
      POSTGRES_DB: hustforces
      POSTGRES_USER: hustforces
      POSTGRES_PASSWORD: hustforces123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hustforces-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U hustforces" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: hustforces-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - hustforces-network

networks:
  hustforces-network:
    driver: bridge

volumes:
  data:
  postgres_data: