spring:
  application:
    name: hustforces
  datasource:
    url: jdbc:postgresql://localhost:5432/judge0
    username: judge0
    password: YourPasswordHere1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

mount:
  path: ${user.dir}/problems

judge0:
  uri: http://localhost:2358

server:
  port: 8080
  base-url: ${SERVER_BASE_URL:https://ac4e-2001-ee0-40c1-c8fd-9050-b146-787e-a65d.ngrok-free.app}

logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  level:
    root: INFO
    com.hust.hustforces: DEBUG
    org.springframework: INFO
    org.hibernate: INFO

jwt:
  secret: yourSecretKeyHereShouldBeAtLeast32CharactersLong
  expiration: 86400000
