spring:
  application:
    name: hustforces

  # Database connection (PostgreSQL)
  datasource:
    url: jdbc:postgresql://localhost:5432/judge0
    username: ${DB_USERNAME:judge0}
    password: ${DB_PASSWORD:YourPasswordHere1234}
    driver-class-name: org.postgresql.Driver

  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # Add batch size for better performance with large updates
        jdbc:
          batch_size: 50

  # Redis configuration (for leaderboard)
  data:
    redis:
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:YourPasswordHere1234}
      username: default
      timeout: 5000
      host: localhost

  # RabbitMQ configuration
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

  # Cache configuration
  cache:
    type: redis
    redis:
      time-to-live: 86400000
      cache-null-values: false
    cache-names: problems, allProblems

  # Task execution config for async tasks
  task:
    execution:
      pool:
        core-size: 4
        max-size: 10
        queue-capacity: 100
        keep-alive: 60s

    # Scheduling config for background tasks
    scheduling:
      pool:
        size: 5
      thread-name-prefix: hustforces-scheduler-

  # Allow overriding bean definitions (needed for some configurations)
  main:
    allow-bean-definition-overriding: true

# Mount path for problems
mount:
  path: ${MOUNT_PATH:${user.dir}/problems}

# Judge0 API configuration
judge0:
  uri: ${JUDGE0_URI:http://localhost:2358}

# Server configuration
server:
  port: 8080
  base-url: ${SERVER_BASE_URL:https://f375-2001-ee0-40c1-f134-80be-acd5-6130-481d.ngrok-free.app}

# Logging configuration
logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  level:
    root: INFO
    com.hust.hustforces: DEBUG
    org.springframework: INFO
    org.hibernate: INFO
    com.hust.hustforces.service.impl.ProblemServiceImpl: DEBUG
    com.hust.hustforces.service.impl.ProblemCacheService: DEBUG
    com.hust.hustforces.utils.ProblemFileUtil: DEBUG
    # Add logging for scheduling and async operations
    org.springframework.scheduling: INFO

# JWT configuration
jwt:
  secret: ${JWT_SECRET:yourSecretKeyHereShouldBeAtLeast32CharactersLong}
  expiration: 86400000  # 24 hours in milliseconds

# Problem configuration
problem:
  preloading:
    enabled: true

# Thread pool configuration for other executor services
executor:
  core-pool-size: 5
  max-pool-size: 10
  queue-capacity: 25
  thread-name-prefix: hustforces-async-